'''
Transcribe a DNA into RNA
Search whether this DNA encodes a given peptide in both directions / all 6 reading frames
'''

import urllib2
URL = 'https://stepic.org/media/attachments/lessons/96/RNA_codon_table_1.txt'
codon_table_file = urllib2.urlopen(URL)
#codon_table_file =open('RNA_codon_table.txt')
CODON_TABLE = {}
REVERSE_CODON_TABLE ={}

for line in codon_table_file.readlines():
    # Construct CODON TABLE dict
    entry = line.split()
    if len(entry) > 1:
        CODON_TABLE[entry[0]] = entry[1]
#        REVERSE_CODON_TABLE.update([entry[1], entry[0]])
    else:
        CODON_TABLE[entry[0]] = '*'
        

def reverse_complement(seq):
    code = {'A':0,'C':1,'G':2,'T':3}
    code_r = {0:'A', 1:'C', 2:'G', 3:'T'}
    rc_seq = ''
    for nt in seq:
        rc_seq = code_r[3 - code[nt]]+ rc_seq
    return rc_seq

#print reverse_complement('AATGA')

def transcription(dna_seq):
    return dna_seq.replace('T','U')

def search(dna_seq, peptide, strand):  
    rna_seq = transcription(dna_seq)  
    for i in range(3):
        pep_read = ''
        for j in range(len(peptide)):
            pep_read += CODON_TABLE[rna_seq[i + j * 3: i + j * 3 + 3]]
#            print pep_read, rna_seq[i + j * 3: i + j * 3 + 3]
#        print rna_seq[i: i + 3 * len(peptide)], pep_read
        if pep_read == peptide:
            if strand == 1:
                print dna_seq[i: i + len(peptide * 3)]
            else:
                print reverse_complement(dna_seq[i: i + len(peptide * 3)])
                                         
        for j in range(len(peptide), len(rna_seq) / 3 - len(peptide) + 1):
            pep_read = pep_read[1 : ] + CODON_TABLE[rna_seq[i + j * 3 : i + j * 3 + 3]]
#            if len(pep_read) != 8:
#                print rna_seq[i + j * 3 - (len(peptide) - 1 ) * 3: i + j * 3 + 3], pep_read, i, j, i + j * 3, i + j * 3 + 3
            if pep_read == peptide:
#                print i , j, pep_read
                if strand == 1:
                    print dna_seq[i + j * 3 - (len(peptide) - 1 ) * 3 : i + j * 3 + 3]
                else:
                    print reverse_complement(dna_seq[i + j * 3 - (len(peptide) - 1 ) * 3 : i + j * 3 + 3])
                        
            
#dna = 'ATGGCCATGGCCCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA' #len = 51
#peptide = 'MA'

dna = 'CGGCGTGCCGGTTTTACGCGGTTGGAACGCGGCGCATTGAAACATGGCTGCCTAGACTGCTATTAGCCCGGTGCGATGATTGACATGGTTGGATATAAGGTTAACCCAAGAGGTGGTACTCATTCGGTAAGGCGCTTCGCCACTGCGGTAATCGCCGTCAGCCGGGCATTGAAGCAAGGTTGGCGCGATTGAGGAAAGGTCCAGGCAGGCAAGAAACCGACGGTTAGCCGTCGCACTTACCAAAGTGCCGAATAATTCGGTCCGGCCGGAGGGATGAAGCTACATGCGCTCTCAACGATGTCTGGTGGGAAGCCTCCGTAGCGCTCCCATTGCTTCAAATTACATCCCATACCCGTGCTCCTATTGACCCAGTCCGGCGGGGGAGATACACCGGTTTGCGGTCACCACAATCCCAACCTGTGGCATTCTGCCGGAATTTCTCCTATCGGTTCGCACGAGGCTGCAATCTCGCCAGCCTTGCTTCAATGCGTGCAGCCAATACTCGCCTTCGATGTCGTGTGGACTAGCTTGATCACGTAAACATTGCTCCACACGACAGAAATAACGGCAAGAGGTAAGCTCATCGACTTTTTCCGATATATCGTCATCATTCGTCGAATTACCCGGTTCCCTCGCTGTTCGTGACACTGCGCTAGTATGCGCTGGCATGACCACCGGCACCTGTCTCATGGCATGTGCTGCTTTTCTGCCACAGACGCAGGCTCAGGTAAATCTAATGTCATGCCGTCTCACGGCCCGTAACCCACACGATTCGTCTGTCATCGACTTAGCTAACTCCCTTCTTGTAGCTGATAAACCGCGCACCACACTACTAGCCGCATGCTGTGCGCATTATATAGGACTTAGAGAATCAGGTTATACACCACCATTTGATTTCGCTCGAGTCACCACATGCGTGCGCAAAGCCTTGTTGCATTAAAACAGGGCTGTCGAGACTGTCACGTTTAAGCATCAACGCATTAAAACAAGGTTGCCTTGACTGGTTAATTCCGATTTGAACACTTTGACAGCAATAAGAAGTTGTTATTGATAAACGCGGCGTGGGCGCCCTTTGGTCGATATAGTCATTGTATAATCTCAGCCCCGCCTTTGTTTTTTGGCCCCTGTACCCAATAATGACGTAGGACGACGGAGATCTTCTGCATAGTACCCTGTCGAGTTGTTAAAATGCTATCTCAGGTTTTCGGTCTACAGAGTGTGGTATGAAACTAAAGTTTATACTGCCAGTTATCGTCCTATCAATCCTTTCACACGACGAATACAAACGGCGTGACTATGGGTTGAATGCGAGTGTCGTCGATGCGCAAATCCGAATGTCGTTCCGTTCACATGGTTCCCCGAGACTTCCGATAGTTGAATCCTTTGAGCCATGGCATCGCAGTCTAGGCAACCTTGCTTCAATGCCTTATAGGCCATCACAGTGCAGAGGTTCGGGACCCCGCAAGGTGAGTAGTCGGTCGCGGCACCCATCTGCAGTGGCGCTACGTCTGGCATCCCTATCTTCGTGAGTTAGAAGTTGGGGTCATCGTGGGGGAGGGATAGAACAGGACGTTCCGTGGTGTCCTGGTGTTAGGTTTTCAAACCGCTATCTGAGATGACGTTTTTCCGACGACACACGTCTGTTGTGGATACCGTCCTTCCACAGCCAGCTAGACGCGCCCCGTACTTCCGATGATCAATAACTATCTTGACTTCCGCACCAACCTGGCCGTCCTTCACGGTATGGGCTCGGAAGAATCCCGACAGACTAAAGGTAAGACCTATTCCCGCGTAAGTGAGACAGCGGAGTTCCACTCCCAACAGAGGATCTAGGCCCGAACGGTAAGCGGTTCAGGACAAGGGTTAAGTTTGCATTCGCAGAGCCTGCGTGGGGTTGCCTTAGTATTACTCGTCTGCTCGGCCTTATCAACCCCGAACTTCATTCAGCGAACGCCACTACCAGTCGCGGCAACCTTGTTTTAATGCTTCTGATAGGGTTCGGCGCTCAGCAGATATGGACGAGGTGAACGATCTTCTACGATTTGCAAACTACCAAGGCGCGACGAACGGACCCCGCCGTTACCACTGACGGCATTAGAGGCCACTCTGGCACGTTCCTCCGTCGGTCGCGTCAGAGTGGGCAAAGGATCCTGGACACAACATGGCGAAACGCAATTCACAGCCGAGATTCATGCCCGGGTTCGGCCAACCCGCGCAAATGGGTGATGCGTGTGCAAACGTTACTGAGCCGCGACTACATAGGACGCCGACGGATGTCGATTAACACTGCACAGGGATGTAGCTCACAACATCACTTGACCGAGCAAAGACATTATCGACTAAGCGAGACTCGTGGTCGGCCCCTGTTTCGTGCTTATTGGTCATGAGTAGGACTACCATCCACTGGGGTGCCTTTCGAACCGGACGATGTGCTGACCAGCTCGATCTCAGCCTTGTCGCCAGTTTAGGCTATTTGCCGATCTTCAGCTACCAATCGTAGGGCCCGTAGCTACATTCATACAAACTTGTCGCCCCGGGCATAATTCATATTTTCTTGCATCAAAGGCATCTAGAGGCTGGTTATAAACCGGTTATCGAGGGCCGTTGCCACCGGCCCTAGTCAACGAAACTTAGTAGTGACGTATCCACTACGGGATCTCCGTACGCGATCAGATATGCAGCTCGTGAGTTATATGTAACGTAACGCGCGGTTCAATACGATCCATATTAAAGCGATGTCCTAGCAAAAGGGGCCGAGATCGCTAAGGCCCGGTCCCCAGCAAAGGGGTCTGTGAATTTATTCTACTCAAACCATCCCCTCTTAAGCGCAACACTCACCCCCCTTTGTTTTTACGTAATTCCGATGTTATGTGGGCAAAAGAACATCAGTCTTAACAATCCAGCCGCATTGAAGCAAGGTTGGCGCAGAGTAGGCAGCCGTGCTTCAATGCTAACGCTCGGCATAGTATGGCAGATACGTCCATTTTTTATTTATTTGCGAAGTCCTCAGTCGCGACAGCCGTGCTTCAACGCCGCCTCTTTACCACTCCGCACGGACTTTTACAGACTCGGTTACTTGCGTAGTTAACTAAGCGAGCAACAGTTGGAGTACCTTGATTCGGGGTAGCCTCCAGAATCGAATCGTACGTGGGGATTACTCTGAATATAGTGATATTTATCAGCTTAGCGCAAAAGACGAAAACCGCGATGTATGGAGACGTGCCCAAAACTGACATGTCATCTATTATTCTCAGGCTAATCATTACAATAATCTCCTCGCGTAGCAATTCTTTCTCGTGCGTTCCAAATTATTGATGGAAGACAGGCTGTTTGCGTGGGGACGACCCATATGTCAGACTAAGAACGTCCCCCCCAGCAGTTAACTAGCGAAGTGACGGGATTGACCCGTTGACTTTAAGTAATCAATTGAACTATACGTGTGAGTCTCGCCTGTGTCGCTGATAAGGTTAACTTAGTCAAAGGCGTCGCATCAATCACGCCAACCTTGTTTCAACGCAAGAAACCGTCGACGCGAGGTCACGCCGGAGGGCAATGCCCAGAAATGATCGGGGGTCCGAAGAAAGACCGGTAAACGAGGGCAAATAAGGGCCGTGCCCCTGCACAAAGCCGAGCATTGAAACACGGTTGCCTGGACTGATCCGTTACTTGTCCACTATACAGACCAATAGGTGTAGACTGGCGGTGATGGTCATAACCAACGGCTTCCCAGACAAAGCTCTGTTGCCTCGCGCATCTGAAACCAACCCATAATTCCGTAGTATGCTTCTGTTCAGCCAGTATCCGCGACAAGAAGCGTGTTTCTGTCTAGTCCGATATATGCCCAATGCAGACGCACAAGATGGGTGTTTACGAGACGACCGCCTTAAAAGTTAATACGTCAAGTCATTTGGACGTTGCAAGGCATCGACCAGGAAAAGTCCTGTGGGAATCCAGGACCTTAGGTGGCGGGGTCGGGGCGAGATAAAATCACAATGCATCTGGACGGTTGGTTGTGGCCGAGTATAGGTTAAAGAGCGGTGGTTGAGAAGACTTCAAGCTACTCATCACCGCTGGAATCATGAACGTACTCGGCGGGCGAGTGGCATTGTATTGAGAAAGGAGAGTTTTTGAGCTAGCAATCGGGGCGAGCGCGATGGAGTTTGGCAGCGCACTGTAGGCAGAGTGTGTTACTTACAACTTGGCACGGTACCGCTAACTCCCTCTCGGGGTGATTGTCGTAAGCAGTCTGGCACTCGGCGTCTCTCTTTCGAGCATAGCCATGTGTCCACGTAGGTACTTTCGTGTTCGAGATCGCCCTGATTGTGCCGATTTCCACAGCGACTTATGGGGCGACCAGTCTCTGAAAAAGACCGACGCCTGGAAGCTTACCAGCGTTCACCTCGTCCTCTGCGACGATACAAATTTTTGCACGTTATAACTTAAGTGACACACAGTTTTGGCGCAGTGCCCAGGATAGAGGCTTGAGGTAGTCTCGATATTCGTGTTAACAGCAACCACAACCCTCGAGTAGCTAATGTCCAATTAACTTCGGTCTTGACAATAAGTCTGATGGATTGTGTCGACTTCACGGGCTTCCTCGCTCCTTCCACCGCTACCCATCGCAAGCCTTTATCGGCATATAGTATTAGAGGTGACGTATGGGGGATCGCGTTGAAGCAAGGTTGACGGGATTGTCTTGTAATCATATCATGCTAGGTCCGTTGATTCCGAGACCACATAAACTTGACAGCTAACTCTAAAAAACCTTGAGGACTACTGGATATACGAGGGCCGTAGTTCTGGTGTCTATAAATCTATGGCACATAGATTAATATGAACAAGCCGGGGCCCTAGGAGAGTTTGGAGCAGTATATGATGATACCCAAGCGGCGCGCATGTCTGCTGCTGTGGTCTACTTGATGCTCGTTTTCAAAGTCGTCAACCTTGCTTTAACGCCAAGACGCCCCAAACTAATACAGTGATGCGCCCCTGATTTCCTCACCTCTCAGCCACACAACACATGACGAGCTGTGCGTTATTGAGAGCCAGAACCCGTACAGCCTTACAGATGGGTCCTTAAGGTCCCCAGGACCACACTGAGTGGAGTGGAGATGCCTTGTTACAATTCACATATGTGTTGAGCGCAAATGGCAAACCAGGAGATTAGAAGACTATCGAGGATCAATTGTCAATCCAGTCCGGGTAGACCATTCAATCGCATTAAAACAAGGTTGCCGCGATTGTTAAAGCCAAAAGGGTGAATCCTGAACAACTCAAAACCAATGTACACAGTCTGTCCGGGTACCCCGGCACTAGGACTAATGACAACTCTCTAAGCTCAGGAGGGAAATCATCATCCTTAATCGCCCTACTCGCGGAATACGCAATCCATATCCTTCTTCACAACAGTTGTCATAGTGGGAGGCTTGAGCCTTAGGGGGAGCTTAGATGCTAGCAGAGCCCTTACTTTCTAGAGGAGTGCATAATGGGTGCTATGTGCATAAAAGGCAGACTCTCCCCATACTTGCTTTGCAGTCTCGGCAGCCTTGTTTCAACGCTCATCCCTACAATGCGCTGTCGGGCGTTTTCTGCCCTAAACAATGCGATTAACGACACTAGATACTGTCCTTGGGGTGAGAGCCAAACTCCCCGACTGGCTATTGCGCTCGACAGAATATCATAACTCTACAGGGGAACGATGACAAAGCAGACAACCCTGCTTTAACGCGCCATACTAATAATATCCGTGCGCGTCGAATGCTGTTCCGTTCTTGACGGCCCCCGATTACTTCCTTGTCCAGTCACAAGGACCCTAGCACCGTCAGATTCACAGGCGAGCTATTCATAGACTTCATTGGAATGGTGCAGAGATCACCACCCGCTACTGCTGTTCACATGCCAGATGGTTATAGAACCTGGGAGATAGCGCTAAAGCAACGAGGATTAGCAGACGGGTCTATAATCCGCTATGGTAGAAATGCACCGCTTACACCTCACTGCATCGCCTGCCTTTAGAATGTGGCCGTAGAACATGTGCTGCATAACAGACCATAGCCCTAACGGTGTAGCAACCCTCGTCACTGGACCCCTGTGTGTAACAGGTTGCATGATCACCTTCAATCATGCCATGCCGACACATACACAACGGGCGCTGATGTATTGCCGACACATAGAACACGGCGTGGAGTACCTTAGTTTCATGAGGTCCTAAGCCTATTATTAGTTGAAGGCGGTCACTGATCAGGCTTTGATAAGAATCTACGTGTGACTTAGACTAGTGATCTCCTTACGCTCGAGCTTTCGTTCGCCCAAAGCGCTCGGACGCCCCTTTAAGATCCACCCGCCGACACTCATCTTTCGTCACCGCGGTACCAGCGCTGTTCCTCTCTAAGCGTCTGGCGCCGCAAAACTGTCGACGTCAAATTACTGGACGGATACCAATATGCTGATCGTCAGGACAATTAATTGGCGGCCTAGGTTCTTGCCTTCGATCCCACGGACGTTGATTATAGCCTGAATCACTCGTACGCAAGAGCACTTTCTGAATATAATTCCATTAGCAAACAGCAGAATACTGCCGTACCGTCCATTGCAATGATCACATTTGCCCTCGAGAAGCGAAAGTAGTACCTACGACTTTCTAGATGTCATCTCACATTCCGCTCTTCCAACACGCTGTACATTATTTCATAACCCAGCCCCGTGAACTGCTGTCGAACCAGCTGACGCGAGCTAACTAATTAGATTACTTCGCCGCAATTAGCGCCGCTGTGAGGGTCGTAGAGGTCTTCACCGAGCACGCCGTTGGCTGTGAAAGCACTGGCCAATACCGTTTACTGAAAAGCGAACCGGCTGCAAACGTCAAAGGCTCATTCCTTGACGCCTCCGCGGAGCGCCTATGCAGAGGAGCTATTAGGAGCATTCCGCATCTCCAGAACATATGAATTCAGCTGACAGAAGTCTGTGGTCGTACACTTTTAAGCATACAGACCACACCTAGCCTGAGCGGGGATCAACCCAGGGTGCTGGTCAATTGCGCATTAAGGATGTTCATACTTATAGCTTTAAGCACGAGAGCGTTGAAACACGGCTGCCTACTTTGACCCTAATCTGTTTAAGGCACACCATCTGTGTGCGTTGAAACATGGCTGGCGACTCTGCGAGCAAAACTTTTCTCGATCTTCTTTTGAACTATATCATTTCCGTCAGAGAAATCGACCGTTCGTTAACGTTAGATCAACCAAACGGGCCCTCGTTAGTGTAAGTTAGCTTTACTGCGAAGCACGGCGTTTGGGCAACCCCCGATCTTCGTACACGATCGACATAGAAAGCCGATTTTGTTCTGGACGGATCCGCTACCTAGGAGCCGCAACTAGAGTGTCAAAACTATTATTATGGGTCTTTACAGTAGCAACATCTGCCTGCTTCGTGCTAGACAGTTCGCCAGCCTCCCAGAGCTGTTAAGTTCAGCATCATTCCCAAGAGTGAACGATTAAGTAGATGCAGACTTTGAATCCGTCCGAGGAACACCTTCAAAGGGCCCAAAATAGTATAGTAAGCCGAACAAGATAGGGATGAGTAGGGTCATGTCATTGCTATGTCCAGCCACTCCCCCCTCAATACCAGGACTAAGGAAGCATAAAGACACAGTATCGTAATTATTTCCCCCGCGTCGTTGTGTGTCATACACCGCTGCGCGTGGTACTACGTGCAGCGCTATGATAATGGGGCGGTGGAAATACCTGGGATGTTATAAAGGTTAAGATCCTCGGTACGGCCTCCGGAAAATCCAGGGATCACACCGGTACCCTAATTGCTGCCTTAAGCATACAAAAGCGAAGTGAGAGCTGGGTTTAGGACTACTGCATAATTTATCCATCCCAAACAGCTAACACATCAGAATTTTGTATTGAACAACTGCCAGGCCATGTGAACATTTGATAAGAGCCGGATGCAGAAGAACGCGGGCTTAGCTAATCGTTTGCTATCGCAGGATCCTGTGTCATGTACCTGGAGAACTTGTAATCGTGTGCCAATAAAGAAGATTCAGTACTCTACTGTGCCGTCTGCTCGGCTGTCGGGTCTGCCTTCATCAGCCCCCCCATGTACGCCCAGTGGCTGTCCTCCGGCATCTCCAAGGACAGAGGTTGTCTCTAACATGGGCAGCACTAACGTGGTGGATCCGCTAAGTTACATTTCGAGTGATTTAGGAATGACAAATAAATCAGCCTCTTCCCGTCGGAACTAGGTACCTCAAACATGCTAAATGTTAGGTAAGACTA'
peptide = 'QSRQPCFNA'


URL = 'https://stepic.org/media/attachments/lessons/96/B_brevis.txt'

file = urllib2.urlopen(URL)
dna = ''.join(ch for ch in file.read() if ch.isalpha())
peptide = 'VKLFPWFNQK'
rc_dna = reverse_complement(dna)

search(dna, peptide, 1)
search(rc_dna, peptide, -1)

  
                                
